### ISSUE TITLE
Error creating permission and checking permissions

### ISSUE THREAD

**Issue by JulianoT** [MarkVilludo/laravel-user-management#1]
Hello,

I'm trying to use your package with laravel 5.6. I installed following your instructions and I ran the migrations, but I think something is missing.

When creating a permission, there is another column on table that should be passed as argument, right? On your documentation is written:

```
use MarkVilludo\Permission\Models\Permission;
$permission = Permission::create(['name' => 'edit articles']);
```

The above code will give an error, since the column "module" isn't parsed on the create function:

`SQLSTATE[HY000]: General error: 1364 Field 'module' doesn't have a default value (SQL: insert into permissions (name, updated_at, created_at) values (edit articles, 2018-08-15 11:46:23, 2018-08-15 11:46:23))`

I created a permission like this:

`$permission = Permission::create(['name' => 'edit articles', 'module' => 'articles']);`

and it works as expected.

However, giving permission to an user will throw an error:

```
$user = Auth::user();
$user->givePermissionTo('edit articles');
```

`MarkVilludo \ Permission \ Exceptions \ PermissionDoesNotExist
No message`

The permission is properly stored on the database, but I'm not sure if what I'm doing is the proper way to give users permission, since it says the permission doesn't exists. 

Your package is really easy to use and very powerfull, I want it to work so I can test it further.

Hope to hear from you soon.

Regards

**Comment by MarkVilludo** [comment]
Hi Sir Juliano T.

Thanks for using one of my package.

I will update the documentations on creating new permissions.
Its already has module name so it can display each permissions per module
and I'll check the error you encountered  to know why its not working with
you.


Regards,

*Mark Villudo*

**Comment by MarkVilludo** [comment]
Just reinstall it again it will works fine sir @JulianoT . Thanks

**Comment by JulianoT** [comment]
Thanks, I'll give it a try. Regards
